// <auto-generated />
namespace DoAnWebBanHang.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class updateusersV2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateusersV2));
        
        string IMigrationMetadata.Id
        {
            get { return "202112201639053_update-usersV2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
