// <auto-generated />
namespace DoAnWebBanHang.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddASPIdentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddASPIdentity));
        
        string IMigrationMetadata.Id
        {
            get { return "202109270442516_Add-ASPIdentity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
